# Generated by Django 3.1.1 on 2020-10-14 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dateCreated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
